/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barab
 */
public class TelaInfoMae extends javax.swing.JFrame {

    /**
     * Creates new form TelaInfoMae
     */
    public TelaInfoMae() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpCategorias = new javax.swing.JTabbedPane();
        pnlDados = new javax.swing.JPanel();
        pnlMae = new javax.swing.JPanel();
        lblNomeMae = new javax.swing.JLabel();
        txtNomeMae = new javax.swing.JTextField();
        lblDataNascMae = new javax.swing.JLabel();
        txfDataNascMae = new javax.swing.JFormattedTextField();
        lblCPFMae = new javax.swing.JLabel();
        txtCPFMae = new javax.swing.JTextField();
        lblRGMae = new javax.swing.JLabel();
        txtRGMae = new javax.swing.JTextField();
        pnlAcomp = new javax.swing.JPanel();
        lblNomeAcomp = new javax.swing.JLabel();
        txtNomeAcomp = new javax.swing.JTextField();
        lblParentescoAcomp = new javax.swing.JLabel();
        txtParentescoAcomp = new javax.swing.JTextField();
        lblCPFAcomp = new javax.swing.JLabel();
        txtCPFAcomp = new javax.swing.JTextField();
        lblRGAcomp = new javax.swing.JLabel();
        txtRGAcomp = new javax.swing.JTextField();
        lblEmailAcomp = new javax.swing.JLabel();
        lblTelAcomp = new javax.swing.JLabel();
        txtTelAcomp = new javax.swing.JTextField();
        txtEmailAcomp = new javax.swing.JTextField();
        lblSexoAcomp = new javax.swing.JLabel();
        cmbSexoAcomp = new javax.swing.JComboBox<>();
        ckbNaoPossuiAcomp = new javax.swing.JCheckBox();
        btnDesfazerAlteracDados = new javax.swing.JButton();
        btnSalvarAlteracDados = new javax.swing.JButton();
        pnlFilhos = new javax.swing.JPanel();
        scrFilhos = new javax.swing.JScrollPane();
        tblFilhos = new javax.swing.JTable();
        btnAddFilho = new javax.swing.JButton();
        btnEditFilho = new javax.swing.JButton();
        btnExcluirFilho = new javax.swing.JButton();
        pnlMedicos = new javax.swing.JPanel();
        btnDesfazerAlteracMedicos = new javax.swing.JButton();
        pnlMedicosRespons = new javax.swing.JPanel();
        scrMedicosRespons = new javax.swing.JScrollPane();
        tblMedicosRespons = new javax.swing.JTable();
        btnRemoverDosMedicosRespons = new javax.swing.JButton();
        lblCRMMedicoRespons = new javax.swing.JLabel();
        txtCRMMedicoRespons = new javax.swing.JTextField();
        btnBuscarMedicoRespons = new javax.swing.JButton();
        pnlTodosMedicos = new javax.swing.JPanel();
        scrTodosMedicos = new javax.swing.JScrollPane();
        tblTodosMedicos = new javax.swing.JTable();
        btnAddAosMedicosRespons = new javax.swing.JButton();
        lblCRMMedico = new javax.swing.JLabel();
        txtCRMMedico = new javax.swing.JTextField();
        btnBuscarMedico = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informações sobre a mãe - Maternidade");

        pnlMae.setBorder(javax.swing.BorderFactory.createTitledBorder("Mãe"));

        lblNomeMae.setText("Nome:");

        lblDataNascMae.setText("Data de nascimento:");

        try {
            txfDataNascMae.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCPFMae.setText("CPF:");

        lblRGMae.setText("RG:");

        javax.swing.GroupLayout pnlMaeLayout = new javax.swing.GroupLayout(pnlMae);
        pnlMae.setLayout(pnlMaeLayout);
        pnlMaeLayout.setHorizontalGroup(
            pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMaeLayout.createSequentialGroup()
                        .addComponent(lblNomeMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDataNascMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfDataNascMae, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMaeLayout.createSequentialGroup()
                        .addComponent(lblCPFMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPFMae))
                    .addGroup(pnlMaeLayout.createSequentialGroup()
                        .addComponent(lblRGMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRGMae)))
                .addContainerGap())
        );
        pnlMaeLayout.setVerticalGroup(
            pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeMae)
                    .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataNascMae)
                    .addComponent(txfDataNascMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFMae)
                    .addComponent(txtCPFMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRGMae)
                    .addComponent(txtRGMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAcomp.setBorder(javax.swing.BorderFactory.createTitledBorder("Acompanhante"));

        lblNomeAcomp.setText("Nome:");

        lblParentescoAcomp.setText("Parentesco:");

        lblCPFAcomp.setText("CPF:");

        lblRGAcomp.setText("RG:");

        lblEmailAcomp.setText("Email:");

        lblTelAcomp.setText("Telefone:");

        lblSexoAcomp.setText("Sexo:");

        cmbSexoAcomp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        cmbSexoAcomp.setMinimumSize(new java.awt.Dimension(89, 26));
        cmbSexoAcomp.setPreferredSize(new java.awt.Dimension(89, 26));

        ckbNaoPossuiAcomp.setText("Não possui");

        javax.swing.GroupLayout pnlAcompLayout = new javax.swing.GroupLayout(pnlAcomp);
        pnlAcomp.setLayout(pnlAcompLayout);
        pnlAcompLayout.setHorizontalGroup(
            pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcompLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblNomeAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeAcomp))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblParentescoAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParentescoAcomp, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblCPFAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPFAcomp))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblRGAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRGAcomp))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblTelAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSexoAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSexoAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblEmailAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailAcomp))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(ckbNaoPossuiAcomp)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAcompLayout.setVerticalGroup(
            pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcompLayout.createSequentialGroup()
                .addComponent(ckbNaoPossuiAcomp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeAcomp)
                    .addComponent(txtNomeAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblParentescoAcomp)
                    .addComponent(txtParentescoAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFAcomp)
                    .addComponent(txtCPFAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRGAcomp)
                    .addComponent(txtRGAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailAcomp)
                    .addComponent(txtEmailAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelAcomp)
                    .addComponent(txtTelAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexoAcomp)
                    .addComponent(cmbSexoAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDesfazerAlteracDados.setText("Desfazer");

        btnSalvarAlteracDados.setText("Salvar");

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAcomp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMae, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarAlteracDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesfazerAlteracDados)))
                .addContainerGap())
        );

        pnlDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDesfazerAlteracDados, btnSalvarAlteracDados});

        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesfazerAlteracDados)
                    .addComponent(btnSalvarAlteracDados))
                .addContainerGap())
        );

        tbpCategorias.addTab("Dados pessoais e do acompanhante", pnlDados);

        tblFilhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Identificador", "Nome", "Sexo", "Altura (cm)", "Peso (kg)", "Data nasc"
            }
        ));
        scrFilhos.setViewportView(tblFilhos);

        btnAddFilho.setText("Adicionar");

        btnEditFilho.setText("Editar");

        btnExcluirFilho.setText("Excluir");

        javax.swing.GroupLayout pnlFilhosLayout = new javax.swing.GroupLayout(pnlFilhos);
        pnlFilhos.setLayout(pnlFilhosLayout);
        pnlFilhosLayout.setHorizontalGroup(
            pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilhosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilhosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluirFilho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditFilho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFilho)))
                .addContainerGap())
        );

        pnlFilhosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddFilho, btnEditFilho, btnExcluirFilho});

        pnlFilhosLayout.setVerticalGroup(
            pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilhosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFilho)
                    .addComponent(btnEditFilho)
                    .addComponent(btnExcluirFilho))
                .addContainerGap())
        );

        tbpCategorias.addTab("Filhos", pnlFilhos);

        btnDesfazerAlteracMedicos.setText("Desfazer alterações");

        pnlMedicosRespons.setBorder(javax.swing.BorderFactory.createTitledBorder("Médicos responsáveis"));

        tblMedicosRespons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Especialidade", "CRM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrMedicosRespons.setViewportView(tblMedicosRespons);

        btnRemoverDosMedicosRespons.setText("Remover dos médicos responsáveis");

        lblCRMMedicoRespons.setText("CRM:");

        btnBuscarMedicoRespons.setText("Buscar na lista");

        javax.swing.GroupLayout pnlMedicosResponsLayout = new javax.swing.GroupLayout(pnlMedicosRespons);
        pnlMedicosRespons.setLayout(pnlMedicosResponsLayout);
        pnlMedicosResponsLayout.setHorizontalGroup(
            pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrMedicosRespons, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRemoverDosMedicosRespons))
                    .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                        .addComponent(lblCRMMedicoRespons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCRMMedicoRespons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarMedicoRespons)))
                .addContainerGap())
        );
        pnlMedicosResponsLayout.setVerticalGroup(
            pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCRMMedicoRespons)
                    .addComponent(txtCRMMedicoRespons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMedicoRespons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrMedicosRespons, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverDosMedicosRespons)
                .addContainerGap())
        );

        pnlTodosMedicos.setBorder(javax.swing.BorderFactory.createTitledBorder("Todos os médicos"));

        tblTodosMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Especialidade", "CRM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrTodosMedicos.setViewportView(tblTodosMedicos);

        btnAddAosMedicosRespons.setText("Adicionar aos médicos responsáveis");

        lblCRMMedico.setText("CRM:");

        btnBuscarMedico.setText("Buscar na lista");

        javax.swing.GroupLayout pnlTodosMedicosLayout = new javax.swing.GroupLayout(pnlTodosMedicos);
        pnlTodosMedicos.setLayout(pnlTodosMedicosLayout);
        pnlTodosMedicosLayout.setHorizontalGroup(
            pnlTodosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTodosMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTodosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTodosMedicosLayout.createSequentialGroup()
                        .addComponent(scrTodosMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(pnlTodosMedicosLayout.createSequentialGroup()
                        .addComponent(btnAddAosMedicosRespons)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlTodosMedicosLayout.createSequentialGroup()
                        .addComponent(lblCRMMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCRMMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarMedico)
                        .addContainerGap())))
        );
        pnlTodosMedicosLayout.setVerticalGroup(
            pnlTodosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTodosMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTodosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCRMMedico)
                    .addComponent(txtCRMMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMedico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrTodosMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAosMedicosRespons)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMedicosLayout = new javax.swing.GroupLayout(pnlMedicos);
        pnlMedicos.setLayout(pnlMedicosLayout);
        pnlMedicosLayout.setHorizontalGroup(
            pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosLayout.createSequentialGroup()
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedicosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDesfazerAlteracMedicos))
                    .addGroup(pnlMedicosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlMedicosRespons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTodosMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMedicosLayout.setVerticalGroup(
            pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMedicosRespons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTodosMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesfazerAlteracMedicos)
                .addContainerGap())
        );

        tbpCategorias.addTab("Médicos responsáveis", pnlMedicos);

        btnVoltar.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpCategorias)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpCategorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfoMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfoMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfoMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfoMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInfoMae().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAosMedicosRespons;
    private javax.swing.JButton btnAddFilho;
    private javax.swing.JButton btnBuscarMedico;
    private javax.swing.JButton btnBuscarMedicoRespons;
    private javax.swing.JButton btnDesfazerAlteracDados;
    private javax.swing.JButton btnDesfazerAlteracMedicos;
    private javax.swing.JButton btnEditFilho;
    private javax.swing.JButton btnExcluirFilho;
    private javax.swing.JButton btnRemoverDosMedicosRespons;
    private javax.swing.JButton btnSalvarAlteracDados;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox ckbNaoPossuiAcomp;
    private javax.swing.JComboBox<String> cmbSexoAcomp;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCPFAcomp;
    private javax.swing.JLabel lblCPFMae;
    private javax.swing.JLabel lblCRMMedico;
    private javax.swing.JLabel lblCRMMedicoRespons;
    private javax.swing.JLabel lblDataNascMae;
    private javax.swing.JLabel lblEmailAcomp;
    private javax.swing.JLabel lblNomeAcomp;
    private javax.swing.JLabel lblNomeMae;
    private javax.swing.JLabel lblParentescoAcomp;
    private javax.swing.JLabel lblRGAcomp;
    private javax.swing.JLabel lblRGMae;
    private javax.swing.JLabel lblSexoAcomp;
    private javax.swing.JLabel lblTelAcomp;
    private javax.swing.JPanel pnlAcomp;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlFilhos;
    private javax.swing.JPanel pnlMae;
    private javax.swing.JPanel pnlMedicos;
    private javax.swing.JPanel pnlMedicosRespons;
    private javax.swing.JPanel pnlTodosMedicos;
    private javax.swing.JScrollPane scrFilhos;
    private javax.swing.JScrollPane scrMedicosRespons;
    private javax.swing.JScrollPane scrTodosMedicos;
    private javax.swing.JTable tblFilhos;
    private javax.swing.JTable tblMedicosRespons;
    private javax.swing.JTable tblTodosMedicos;
    private javax.swing.JTabbedPane tbpCategorias;
    private javax.swing.JFormattedTextField txfDataNascMae;
    private javax.swing.JTextField txtCPFAcomp;
    private javax.swing.JTextField txtCPFMae;
    private javax.swing.JTextField txtCRMMedico;
    private javax.swing.JTextField txtCRMMedicoRespons;
    private javax.swing.JTextField txtEmailAcomp;
    private javax.swing.JTextField txtNomeAcomp;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtParentescoAcomp;
    private javax.swing.JTextField txtRGAcomp;
    private javax.swing.JTextField txtRGMae;
    private javax.swing.JTextField txtTelAcomp;
    // End of variables declaration//GEN-END:variables
}
