/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TableModelFactory;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Baby;
import model.BabyDAO;
import model.Companion;
import model.CompanionDAO;
import model.DoctorDAO;
import model.Mother;

/**
 *
 * @author barab
 */
public class TelaInfoMae extends javax.swing.JDialog {

    private Mother maeNoBancoDeDados = null;
    private Companion acompNoBancoDeDados = null;

    /**
     * Creates new form DialogCadastrMae
     */
    public TelaInfoMae(java.awt.Frame parent, boolean modal, Mother mother) {
        super(parent, modal);
        this.maeNoBancoDeDados = mother;
        initComponents();
        mostraDadosMae();
        this.acompNoBancoDeDados = CompanionDAO.selectCompanionOf(mother.getCpf());
        if (acompNoBancoDeDados != null) {
            mostraDadosAcomp();
        } else {
            ckbNaoPossuiAcomp.setSelected(true);
            setDadosAcompEnabled(false);
        }
        preencheTabelaBebes();
        preencheTblMedicosRespons();
        preencheTblMedicosDisponiveis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpCategorias = new javax.swing.JTabbedPane();
        pnlDados = new javax.swing.JPanel();
        pnlMae = new javax.swing.JPanel();
        lblNomeMae = new javax.swing.JLabel();
        txtNomeMae = new javax.swing.JTextField();
        lblDataNascMae = new javax.swing.JLabel();
        txfDataNascMae = new javax.swing.JFormattedTextField();
        lblCpfMae = new javax.swing.JLabel();
        lblRgMae = new javax.swing.JLabel();
        txtRgMae = new javax.swing.JTextField();
        txfCpfMae = new javax.swing.JFormattedTextField();
        pnlAcomp = new javax.swing.JPanel();
        lblNomeAcomp = new javax.swing.JLabel();
        txtNomeAcomp = new javax.swing.JTextField();
        lblParentescoAcomp = new javax.swing.JLabel();
        txtParentescoAcomp = new javax.swing.JTextField();
        lblCpfAcomp = new javax.swing.JLabel();
        lblRgAcomp = new javax.swing.JLabel();
        txtRgAcomp = new javax.swing.JTextField();
        lblEmailAcomp = new javax.swing.JLabel();
        lblTelAcomp = new javax.swing.JLabel();
        txtTelAcomp = new javax.swing.JTextField();
        txtEmailAcomp = new javax.swing.JTextField();
        lblSexoAcomp = new javax.swing.JLabel();
        cmbSexoAcomp = new javax.swing.JComboBox<>();
        ckbNaoPossuiAcomp = new javax.swing.JCheckBox();
        txfCpfAcomp = new javax.swing.JFormattedTextField();
        btnDesfazerAlteracDados = new javax.swing.JButton();
        btnSalvarAlteracDados = new javax.swing.JButton();
        pnlFilhos = new javax.swing.JPanel();
        scrFilhos = new javax.swing.JScrollPane();
        tblFilhos = new javax.swing.JTable();
        btnAddFilho = new javax.swing.JButton();
        btnEditFilho = new javax.swing.JButton();
        btnExcluirFilho = new javax.swing.JButton();
        pnlMedicos = new javax.swing.JPanel();
        btnDesfazerAlteracMedicos = new javax.swing.JButton();
        pnlMedicosRespons = new javax.swing.JPanel();
        scrMedicosRespons = new javax.swing.JScrollPane();
        tblMedicosRespons = new javax.swing.JTable();
        btnRemoverDosMedicosRespons = new javax.swing.JButton();
        lblCrmMedicoRespons = new javax.swing.JLabel();
        txtCrmMedicoRespons = new javax.swing.JTextField();
        btnBuscarMedicoRespons = new javax.swing.JButton();
        pnlMedicosDisponiv = new javax.swing.JPanel();
        scrMedicosDisponiv = new javax.swing.JScrollPane();
        tblMedicosDisponiv = new javax.swing.JTable();
        btnAddAosMedicosRespons = new javax.swing.JButton();
        lblCrmMedicoDisponiv = new javax.swing.JLabel();
        txtCrmMedicoDisponiv = new javax.swing.JTextField();
        btnBuscarMedicoDisponiv = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mais informações sobre a mãe");
        setModal(true);
        setResizable(false);

        pnlMae.setBorder(javax.swing.BorderFactory.createTitledBorder("Mãe"));

        lblNomeMae.setText("Nome:");

        lblDataNascMae.setText("Data de nascimento:");

        try {
            txfDataNascMae.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCpfMae.setText("CPF:");

        lblRgMae.setText("RG:");

        try {
            txfCpfMae.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnlMaeLayout = new javax.swing.GroupLayout(pnlMae);
        pnlMae.setLayout(pnlMaeLayout);
        pnlMaeLayout.setHorizontalGroup(
            pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMaeLayout.createSequentialGroup()
                        .addComponent(lblNomeMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeMae, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDataNascMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfDataNascMae, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMaeLayout.createSequentialGroup()
                        .addComponent(lblCpfMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfCpfMae))
                    .addGroup(pnlMaeLayout.createSequentialGroup()
                        .addComponent(lblRgMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRgMae)))
                .addContainerGap())
        );
        pnlMaeLayout.setVerticalGroup(
            pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeMae)
                    .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataNascMae)
                    .addComponent(txfDataNascMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfMae)
                    .addComponent(txfCpfMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRgMae)
                    .addComponent(txtRgMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAcomp.setBorder(javax.swing.BorderFactory.createTitledBorder("Acompanhante"));

        lblNomeAcomp.setText("Nome:");

        lblParentescoAcomp.setText("Parentesco:");

        lblCpfAcomp.setText("CPF:");

        lblRgAcomp.setText("RG:");

        lblEmailAcomp.setText("Email:");

        lblTelAcomp.setText("Telefone:");

        lblSexoAcomp.setText("Sexo:");

        cmbSexoAcomp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino" }));
        cmbSexoAcomp.setMinimumSize(new java.awt.Dimension(89, 26));
        cmbSexoAcomp.setPreferredSize(new java.awt.Dimension(89, 26));

        ckbNaoPossuiAcomp.setText("Não possui");
        ckbNaoPossuiAcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbNaoPossuiAcompActionPerformed(evt);
            }
        });

        try {
            txfCpfAcomp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnlAcompLayout = new javax.swing.GroupLayout(pnlAcomp);
        pnlAcomp.setLayout(pnlAcompLayout);
        pnlAcompLayout.setHorizontalGroup(
            pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcompLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblNomeAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeAcomp))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblParentescoAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParentescoAcomp, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblRgAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRgAcomp))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblTelAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelAcomp, javax.swing.GroupLayout.DEFAULT_SIZE, 1159, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSexoAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSexoAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblEmailAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailAcomp))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(ckbNaoPossuiAcomp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlAcompLayout.createSequentialGroup()
                        .addComponent(lblCpfAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfCpfAcomp)))
                .addContainerGap())
        );
        pnlAcompLayout.setVerticalGroup(
            pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcompLayout.createSequentialGroup()
                .addComponent(ckbNaoPossuiAcomp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeAcomp)
                    .addComponent(txtNomeAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblParentescoAcomp)
                    .addComponent(txtParentescoAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfAcomp)
                    .addComponent(txfCpfAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRgAcomp)
                    .addComponent(txtRgAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailAcomp)
                    .addComponent(txtEmailAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelAcomp)
                    .addComponent(txtTelAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexoAcomp)
                    .addComponent(cmbSexoAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDesfazerAlteracDados.setText("Desfazer");
        btnDesfazerAlteracDados.setEnabled(false);

        btnSalvarAlteracDados.setText("Salvar");
        btnSalvarAlteracDados.setEnabled(false);
        btnSalvarAlteracDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAcomp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMae, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarAlteracDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesfazerAlteracDados)))
                .addContainerGap())
        );

        pnlDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDesfazerAlteracDados, btnSalvarAlteracDados});

        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesfazerAlteracDados)
                    .addComponent(btnSalvarAlteracDados))
                .addContainerGap())
        );

        tbpCategorias.addTab("Dados pessoais e do acompanhante", pnlDados);

        tblFilhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nome", "Sexo", "Altura (cm)", "Peso (kg)", "Data de nascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFilhos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFilhosMouseClicked(evt);
            }
        });
        scrFilhos.setViewportView(tblFilhos);

        btnAddFilho.setText("Adicionar");
        btnAddFilho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFilhoActionPerformed(evt);
            }
        });

        btnEditFilho.setText("Editar");
        btnEditFilho.setEnabled(false);
        btnEditFilho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFilhoActionPerformed(evt);
            }
        });

        btnExcluirFilho.setText("Excluir");
        btnExcluirFilho.setEnabled(false);
        btnExcluirFilho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFilhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFilhosLayout = new javax.swing.GroupLayout(pnlFilhos);
        pnlFilhos.setLayout(pnlFilhosLayout);
        pnlFilhosLayout.setHorizontalGroup(
            pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilhosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, 1342, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilhosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluirFilho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditFilho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFilho)))
                .addContainerGap())
        );

        pnlFilhosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddFilho, btnEditFilho, btnExcluirFilho});

        pnlFilhosLayout.setVerticalGroup(
            pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilhosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFilho)
                    .addComponent(btnEditFilho)
                    .addComponent(btnExcluirFilho))
                .addContainerGap())
        );

        tbpCategorias.addTab("Filhos", pnlFilhos);

        btnDesfazerAlteracMedicos.setText("Desfazer alterações");
        btnDesfazerAlteracMedicos.setEnabled(false);

        pnlMedicosRespons.setBorder(javax.swing.BorderFactory.createTitledBorder("Médicos responsáveis"));

        tblMedicosRespons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Especialidade", "CRM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrMedicosRespons.setViewportView(tblMedicosRespons);

        btnRemoverDosMedicosRespons.setText("Remover dos médicos responsáveis");
        btnRemoverDosMedicosRespons.setEnabled(false);

        lblCrmMedicoRespons.setText("CRM:");

        btnBuscarMedicoRespons.setText("Buscar na lista");
        btnBuscarMedicoRespons.setEnabled(false);

        javax.swing.GroupLayout pnlMedicosResponsLayout = new javax.swing.GroupLayout(pnlMedicosRespons);
        pnlMedicosRespons.setLayout(pnlMedicosResponsLayout);
        pnlMedicosResponsLayout.setHorizontalGroup(
            pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrMedicosRespons, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRemoverDosMedicosRespons))
                    .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                        .addComponent(lblCrmMedicoRespons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCrmMedicoRespons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarMedicoRespons)))
                .addContainerGap())
        );
        pnlMedicosResponsLayout.setVerticalGroup(
            pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrmMedicoRespons)
                    .addComponent(txtCrmMedicoRespons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMedicoRespons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrMedicosRespons, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverDosMedicosRespons)
                .addContainerGap())
        );

        pnlMedicosDisponiv.setBorder(javax.swing.BorderFactory.createTitledBorder("Médicos disponíveis"));

        tblMedicosDisponiv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Especialidade", "CRM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrMedicosDisponiv.setViewportView(tblMedicosDisponiv);

        btnAddAosMedicosRespons.setText("Adicionar aos médicos responsáveis");
        btnAddAosMedicosRespons.setEnabled(false);

        lblCrmMedicoDisponiv.setText("CRM:");

        btnBuscarMedicoDisponiv.setText("Buscar na lista");
        btnBuscarMedicoDisponiv.setEnabled(false);

        javax.swing.GroupLayout pnlMedicosDisponivLayout = new javax.swing.GroupLayout(pnlMedicosDisponiv);
        pnlMedicosDisponiv.setLayout(pnlMedicosDisponivLayout);
        pnlMedicosDisponivLayout.setHorizontalGroup(
            pnlMedicosDisponivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosDisponivLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosDisponivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedicosDisponivLayout.createSequentialGroup()
                        .addComponent(scrMedicosDisponiv, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(pnlMedicosDisponivLayout.createSequentialGroup()
                        .addComponent(btnAddAosMedicosRespons)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMedicosDisponivLayout.createSequentialGroup()
                        .addComponent(lblCrmMedicoDisponiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCrmMedicoDisponiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarMedicoDisponiv)
                        .addContainerGap())))
        );
        pnlMedicosDisponivLayout.setVerticalGroup(
            pnlMedicosDisponivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosDisponivLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosDisponivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrmMedicoDisponiv)
                    .addComponent(txtCrmMedicoDisponiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMedicoDisponiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrMedicosDisponiv, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAosMedicosRespons)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMedicosLayout = new javax.swing.GroupLayout(pnlMedicos);
        pnlMedicos.setLayout(pnlMedicosLayout);
        pnlMedicosLayout.setHorizontalGroup(
            pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosLayout.createSequentialGroup()
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedicosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDesfazerAlteracMedicos))
                    .addGroup(pnlMedicosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlMedicosRespons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMedicosDisponiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMedicosLayout.setVerticalGroup(
            pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMedicosRespons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMedicosDisponiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesfazerAlteracMedicos)
                .addContainerGap())
        );

        tbpCategorias.addTab("Médicos responsáveis", pnlMedicos);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1295, Short.MAX_VALUE)
                        .addComponent(btnVoltar)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tbpCategorias)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(521, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(tbpCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbNaoPossuiAcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbNaoPossuiAcompActionPerformed
        if (ckbNaoPossuiAcomp.isSelected()) {
            setDadosAcompEnabled(false);
        } else {
            setDadosAcompEnabled(true);
        }
    }//GEN-LAST:event_ckbNaoPossuiAcompActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarAlteracDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracDadosActionPerformed

    }//GEN-LAST:event_btnSalvarAlteracDadosActionPerformed

    private void btnAddFilhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFilhoActionPerformed
        TelaAddFilho telaAddFilho = new TelaAddFilho(null, true, maeNoBancoDeDados.getCpf());
        telaAddFilho.setLocationRelativeTo(null);
        telaAddFilho.setVisible(true);
        preencheTabelaBebes();
        btnExcluirFilho.setEnabled(false); // Porque nenhum item da tabela estará selecionado.
        btnEditFilho.setEnabled(false);
    }//GEN-LAST:event_btnAddFilhoActionPerformed

    private void tblFilhosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFilhosMouseClicked
        btnEditFilho.setEnabled(true);
        btnExcluirFilho.setEnabled(true);
    }//GEN-LAST:event_tblFilhosMouseClicked

    private void btnEditFilhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFilhoActionPerformed
        int indices[] = tblFilhos.getSelectedRows();
        if (indices.length > 1) {
            JOptionPane.showMessageDialog(this, "Selecione apenas "
                    + "um filho para editar.");
        } else {
            TableModel modelo = tblFilhos.getModel();
            String id = modelo.getValueAt(indices[0], 0).toString();
            Baby baby = BabyDAO.searchById(id);
            TelaEditFilho telaEditFilho = new TelaEditFilho(null, true, baby);
            telaEditFilho.setLocationRelativeTo(null);
            telaEditFilho.setVisible(true);
            preencheTabelaBebes();
            btnExcluirFilho.setEnabled(false); // Porque nenhum item da tabela estará selecionado.
            btnEditFilho.setEnabled(false);
        }
    }//GEN-LAST:event_btnEditFilhoActionPerformed

    private void btnExcluirFilhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFilhoActionPerformed
        int indices[] = tblFilhos.getSelectedRows();
        if (indices.length > 1) {
            int opcao = JOptionPane.showConfirmDialog(null, "Confirma "
                    + "exclusão de vários bebês?", "Confirmação de "
                    + "exclusão", JOptionPane.YES_NO_OPTION);
            if (opcao == JOptionPane.YES_OPTION) {
                for (int indice : indices) {
                    TableModel modelo = tblFilhos.getModel();
                    String id = modelo.getValueAt(indice, 0).toString();
                    BabyDAO.delete(id);
                }
            }
        } else {
            TableModel modelo = tblFilhos.getModel();
            String id = modelo.getValueAt(indices[0], 0).toString();
            BabyDAO.delete(id);
        }
        preencheTabelaBebes();
        btnExcluirFilho.setEnabled(false); // Porque nenhum item da tabela estará selecionado.
        btnEditFilho.setEnabled(false);
    }//GEN-LAST:event_btnExcluirFilhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfoMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfoMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfoMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfoMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaInfoMae dialog = new TelaInfoMae(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAosMedicosRespons;
    private javax.swing.JButton btnAddFilho;
    private javax.swing.JButton btnBuscarMedicoDisponiv;
    private javax.swing.JButton btnBuscarMedicoRespons;
    private javax.swing.JButton btnDesfazerAlteracDados;
    private javax.swing.JButton btnDesfazerAlteracMedicos;
    private javax.swing.JButton btnEditFilho;
    private javax.swing.JButton btnExcluirFilho;
    private javax.swing.JButton btnRemoverDosMedicosRespons;
    private javax.swing.JButton btnSalvarAlteracDados;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox ckbNaoPossuiAcomp;
    private javax.swing.JComboBox<String> cmbSexoAcomp;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCpfAcomp;
    private javax.swing.JLabel lblCpfMae;
    private javax.swing.JLabel lblCrmMedicoDisponiv;
    private javax.swing.JLabel lblCrmMedicoRespons;
    private javax.swing.JLabel lblDataNascMae;
    private javax.swing.JLabel lblEmailAcomp;
    private javax.swing.JLabel lblNomeAcomp;
    private javax.swing.JLabel lblNomeMae;
    private javax.swing.JLabel lblParentescoAcomp;
    private javax.swing.JLabel lblRgAcomp;
    private javax.swing.JLabel lblRgMae;
    private javax.swing.JLabel lblSexoAcomp;
    private javax.swing.JLabel lblTelAcomp;
    private javax.swing.JPanel pnlAcomp;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlFilhos;
    private javax.swing.JPanel pnlMae;
    private javax.swing.JPanel pnlMedicos;
    private javax.swing.JPanel pnlMedicosDisponiv;
    private javax.swing.JPanel pnlMedicosRespons;
    private javax.swing.JScrollPane scrFilhos;
    private javax.swing.JScrollPane scrMedicosDisponiv;
    private javax.swing.JScrollPane scrMedicosRespons;
    private javax.swing.JTable tblFilhos;
    private javax.swing.JTable tblMedicosDisponiv;
    private javax.swing.JTable tblMedicosRespons;
    private javax.swing.JTabbedPane tbpCategorias;
    private javax.swing.JFormattedTextField txfCpfAcomp;
    private javax.swing.JFormattedTextField txfCpfMae;
    private javax.swing.JFormattedTextField txfDataNascMae;
    private javax.swing.JTextField txtCrmMedicoDisponiv;
    private javax.swing.JTextField txtCrmMedicoRespons;
    private javax.swing.JTextField txtEmailAcomp;
    private javax.swing.JTextField txtNomeAcomp;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtParentescoAcomp;
    private javax.swing.JTextField txtRgAcomp;
    private javax.swing.JTextField txtRgMae;
    private javax.swing.JTextField txtTelAcomp;
    // End of variables declaration//GEN-END:variables

    private void setDadosAcompEnabled(boolean isEnabled) {
        lblNomeAcomp.setEnabled(isEnabled);
        lblParentescoAcomp.setEnabled(isEnabled);
        lblCpfAcomp.setEnabled(isEnabled);
        lblRgAcomp.setEnabled(isEnabled);
        lblEmailAcomp.setEnabled(isEnabled);
        lblTelAcomp.setEnabled(isEnabled);
        lblSexoAcomp.setEnabled(isEnabled);

        txtNomeAcomp.setEnabled(isEnabled);
        txtParentescoAcomp.setEnabled(isEnabled);
        txfCpfAcomp.setEnabled(isEnabled);
        txtRgAcomp.setEnabled(isEnabled);
        txtEmailAcomp.setEnabled(isEnabled);
        txtTelAcomp.setEnabled(isEnabled);
        cmbSexoAcomp.setEnabled(isEnabled);
    }

    private void mostraDadosMae() {
        txtNomeMae.setText(maeNoBancoDeDados.getName());
        String dataNasc = maeNoBancoDeDados.getBirthday().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        txfDataNascMae.setText(dataNasc);
        txfCpfMae.setText(maeNoBancoDeDados.getCpf());
        txtRgMae.setText(maeNoBancoDeDados.getRg());
    }

    private void mostraDadosAcomp() {
        txtNomeAcomp.setText(acompNoBancoDeDados.getName());
        txtParentescoAcomp.setText(acompNoBancoDeDados.getKinship());
        txfCpfAcomp.setText(acompNoBancoDeDados.getCpf());
        txtRgAcomp.setText(acompNoBancoDeDados.getRg());
        txtEmailAcomp.setText(acompNoBancoDeDados.getEmail());
        txtTelAcomp.setText(acompNoBancoDeDados.getPhone());
        cmbSexoAcomp.setSelectedItem(acompNoBancoDeDados.getSex());
    }

    private void preencheTabelaBebes() {
        tblFilhos.setModel(TableModelFactory.criarTblModelBebes(BabyDAO.selectSonsOf(maeNoBancoDeDados.getCpf())));
    }

    private void preencheTblMedicosRespons() {
        tblMedicosRespons.setModel(TableModelFactory.criarTblModelMedicos(DoctorDAO.selectResponsibleFor(maeNoBancoDeDados.getCpf())));
    }

    private void preencheTblMedicosDisponiveis() {
        tblMedicosDisponiv.setModel(TableModelFactory.criarTblModelMedicos(DoctorDAO.selectNotResponsibleFor(maeNoBancoDeDados.getCpf())));
    }
}
