/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barab
 */
public class TelaCadastrMae extends javax.swing.JDialog {

    /**
     * Creates new form DialogCadastrarMae
     * @param parent
     * @param modal
     */
    public TelaCadastrMae(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pnlDadosPessoais.setVisible(true);
        pnlFilhos.setVisible(false);
        pnlMedicos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lrpEtapasCadastro = new javax.swing.JLayeredPane();
        pnlDadosPessoais = new javax.swing.JPanel();
        pnlMae = new javax.swing.JPanel();
        lblNomeMae = new javax.swing.JLabel();
        txtNomeMae = new javax.swing.JTextField();
        lblDataNascMae = new javax.swing.JLabel();
        txtDataNascMae = new javax.swing.JFormattedTextField();
        lblCPFMae = new javax.swing.JLabel();
        txtCPFMae = new javax.swing.JTextField();
        lblRGMae = new javax.swing.JLabel();
        txtRGMae = new javax.swing.JTextField();
        pnlAcompanhante = new javax.swing.JPanel();
        lblNomeAcomp = new javax.swing.JLabel();
        txtNomeAcomp = new javax.swing.JTextField();
        lblParentescoAcomp = new javax.swing.JLabel();
        txtParentescoAcomp = new javax.swing.JTextField();
        lblCPFAcomp = new javax.swing.JLabel();
        txtCPFAcomp = new javax.swing.JTextField();
        lblRGAcomp = new javax.swing.JLabel();
        txtRGAcomp = new javax.swing.JTextField();
        lblEmailAcomp = new javax.swing.JLabel();
        lblTelAcomp = new javax.swing.JLabel();
        txtTelAcomp = new javax.swing.JTextField();
        txtEmailAcomp = new javax.swing.JTextField();
        lblSexoAcomp = new javax.swing.JLabel();
        cmbSexoAcomp = new javax.swing.JComboBox<>();
        ckbNaoPossuiAcomp = new javax.swing.JCheckBox();
        btnProxDoPnlDados = new javax.swing.JButton();
        btnCancelarPnlDados = new javax.swing.JButton();
        pnlFilhos = new javax.swing.JPanel();
        btnProxPnlFilhos = new javax.swing.JButton();
        btnAntPnlFilhos = new javax.swing.JButton();
        btnCancelarDoPnlFilhos = new javax.swing.JButton();
        subPnlFilhos = new javax.swing.JPanel();
        scrFilhos = new javax.swing.JScrollPane();
        tblFilhos = new javax.swing.JTable();
        btnAddFilho = new javax.swing.JButton();
        btnEditFilho = new javax.swing.JButton();
        btnExcluirFilho = new javax.swing.JButton();
        pnlMedicos = new javax.swing.JPanel();
        btnCadastrarDoPnlMedicos = new javax.swing.JButton();
        pnlMedicosRespons = new javax.swing.JPanel();
        scrMedicosRespons = new javax.swing.JScrollPane();
        tblMedicosRespons = new javax.swing.JTable();
        btnRemovDosMedicosRespons = new javax.swing.JButton();
        lblCRMMedicoRespons = new javax.swing.JLabel();
        txtCRMMedicoRespons = new javax.swing.JTextField();
        btnBuscarMedicoRespons = new javax.swing.JButton();
        pnlTodosMedicos = new javax.swing.JPanel();
        scrTodosMedicos = new javax.swing.JScrollPane();
        tblTodosMedicos = new javax.swing.JTable();
        btnAddAosMedicosRespons = new javax.swing.JButton();
        lblCRMMedico = new javax.swing.JLabel();
        txtCRMMedico = new javax.swing.JTextField();
        btnBuscarDoPnlTodosMedicos = new javax.swing.JButton();
        btnAntDoPnlMedicos = new javax.swing.JButton();
        btnCancelarDoPnlMedicos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Mãe");
        setIconImage(null);
        setPreferredSize(new java.awt.Dimension(1366, 520));
        setResizable(false);

        pnlMae.setBorder(javax.swing.BorderFactory.createTitledBorder("Mãe"));

        lblNomeMae.setText("Nome:");

        lblDataNascMae.setText("Data de nascimento:");

        try {
            txtDataNascMae.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCPFMae.setText("CPF:");

        lblRGMae.setText("RG:");

        javax.swing.GroupLayout pnlMaeLayout = new javax.swing.GroupLayout(pnlMae);
        pnlMae.setLayout(pnlMaeLayout);
        pnlMaeLayout.setHorizontalGroup(
            pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMaeLayout.createSequentialGroup()
                        .addComponent(lblNomeMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDataNascMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataNascMae, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMaeLayout.createSequentialGroup()
                        .addComponent(lblCPFMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPFMae))
                    .addGroup(pnlMaeLayout.createSequentialGroup()
                        .addComponent(lblRGMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRGMae)))
                .addContainerGap())
        );
        pnlMaeLayout.setVerticalGroup(
            pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeMae)
                    .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataNascMae)
                    .addComponent(txtDataNascMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFMae)
                    .addComponent(txtCPFMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRGMae)
                    .addComponent(txtRGMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAcompanhante.setBorder(javax.swing.BorderFactory.createTitledBorder("Acompanhante"));

        lblNomeAcomp.setText("Nome:");

        lblParentescoAcomp.setText("Parentesco:");

        lblCPFAcomp.setText("CPF:");

        lblRGAcomp.setText("RG:");

        lblEmailAcomp.setText("Email:");

        lblTelAcomp.setText("Telefone:");

        lblSexoAcomp.setText("Sexo:");

        cmbSexoAcomp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino" }));
        cmbSexoAcomp.setMaximumSize(new java.awt.Dimension(89, 26));
        cmbSexoAcomp.setMinimumSize(new java.awt.Dimension(89, 26));
        cmbSexoAcomp.setPreferredSize(new java.awt.Dimension(89, 26));

        ckbNaoPossuiAcomp.setText("Não possui");
        ckbNaoPossuiAcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbNaoPossuiAcompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAcompanhanteLayout = new javax.swing.GroupLayout(pnlAcompanhante);
        pnlAcompanhante.setLayout(pnlAcompanhanteLayout);
        pnlAcompanhanteLayout.setHorizontalGroup(
            pnlAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcompanhanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAcompanhanteLayout.createSequentialGroup()
                        .addComponent(lblNomeAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeAcomp))
                    .addGroup(pnlAcompanhanteLayout.createSequentialGroup()
                        .addComponent(lblParentescoAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParentescoAcomp, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE))
                    .addGroup(pnlAcompanhanteLayout.createSequentialGroup()
                        .addComponent(lblCPFAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPFAcomp))
                    .addGroup(pnlAcompanhanteLayout.createSequentialGroup()
                        .addComponent(lblRGAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRGAcomp))
                    .addGroup(pnlAcompanhanteLayout.createSequentialGroup()
                        .addComponent(lblTelAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSexoAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSexoAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAcompanhanteLayout.createSequentialGroup()
                        .addComponent(lblEmailAcomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailAcomp))
                    .addGroup(pnlAcompanhanteLayout.createSequentialGroup()
                        .addComponent(ckbNaoPossuiAcomp)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAcompanhanteLayout.setVerticalGroup(
            pnlAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcompanhanteLayout.createSequentialGroup()
                .addComponent(ckbNaoPossuiAcomp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeAcomp)
                    .addComponent(txtNomeAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblParentescoAcomp)
                    .addComponent(txtParentescoAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFAcomp)
                    .addComponent(txtCPFAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRGAcomp)
                    .addComponent(txtRGAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailAcomp)
                    .addComponent(txtEmailAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAcompanhanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelAcomp)
                    .addComponent(txtTelAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexoAcomp)
                    .addComponent(cmbSexoAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnProxDoPnlDados.setText("Próximo");
        btnProxDoPnlDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxDoPnlDadosActionPerformed(evt);
            }
        });

        btnCancelarPnlDados.setText("Cancelar");
        btnCancelarPnlDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPnlDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosPessoaisLayout = new javax.swing.GroupLayout(pnlDadosPessoais);
        pnlDadosPessoais.setLayout(pnlDadosPessoaisLayout);
        pnlDadosPessoaisLayout.setHorizontalGroup(
            pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAcompanhante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMae, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosPessoaisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnProxDoPnlDados, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarPnlDados)))
                .addContainerGap())
        );
        pnlDadosPessoaisLayout.setVerticalGroup(
            pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProxDoPnlDados)
                    .addComponent(btnCancelarPnlDados))
                .addContainerGap())
        );

        pnlFilhos.setBorder(null);

        btnProxPnlFilhos.setText("Próximo");
        btnProxPnlFilhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxPnlFilhosActionPerformed(evt);
            }
        });

        btnAntPnlFilhos.setText("Anterior");
        btnAntPnlFilhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntPnlFilhosActionPerformed(evt);
            }
        });

        btnCancelarDoPnlFilhos.setText("Cancelar");
        btnCancelarDoPnlFilhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDoPnlFilhosActionPerformed(evt);
            }
        });

        subPnlFilhos.setBorder(javax.swing.BorderFactory.createTitledBorder("Filhos"));

        scrFilhos.setBorder(null);

        tblFilhos.setBorder(null);
        tblFilhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "", null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Identificador", "Nome", "Sexo", "Altura (cm)", "Peso (kg)", "Data nasc"
            }
        ));
        tblFilhos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblFilhosKeyPressed(evt);
            }
        });
        scrFilhos.setViewportView(tblFilhos);

        btnAddFilho.setText("Adicionar");

        btnEditFilho.setText("Editar");

        btnExcluirFilho.setText("Excluir");

        javax.swing.GroupLayout subPnlFilhosLayout = new javax.swing.GroupLayout(subPnlFilhos);
        subPnlFilhos.setLayout(subPnlFilhosLayout);
        subPnlFilhosLayout.setHorizontalGroup(
            subPnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPnlFilhosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPnlFilhosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluirFilho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditFilho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFilho))
                    .addComponent(scrFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE))
                .addContainerGap())
        );
        subPnlFilhosLayout.setVerticalGroup(
            subPnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPnlFilhosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFilho)
                    .addComponent(btnEditFilho)
                    .addComponent(btnExcluirFilho))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlFilhosLayout = new javax.swing.GroupLayout(pnlFilhos);
        pnlFilhos.setLayout(pnlFilhosLayout);
        pnlFilhosLayout.setHorizontalGroup(
            pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilhosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilhosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAntPnlFilhos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProxPnlFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarDoPnlFilhos))
                    .addComponent(subPnlFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFilhosLayout.setVerticalGroup(
            pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilhosLayout.createSequentialGroup()
                .addComponent(subPnlFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFilhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProxPnlFilhos)
                    .addComponent(btnAntPnlFilhos)
                    .addComponent(btnCancelarDoPnlFilhos))
                .addContainerGap())
        );

        btnCadastrarDoPnlMedicos.setText("Cadastrar");

        pnlMedicosRespons.setBorder(javax.swing.BorderFactory.createTitledBorder("Médicos responsáveis"));

        tblMedicosRespons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Especialidade", "CRM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrMedicosRespons.setViewportView(tblMedicosRespons);

        btnRemovDosMedicosRespons.setText("Remover dos médicos responsáveis");

        lblCRMMedicoRespons.setText("CRM:");

        btnBuscarMedicoRespons.setText("Buscar na lista");

        javax.swing.GroupLayout pnlMedicosResponsLayout = new javax.swing.GroupLayout(pnlMedicosRespons);
        pnlMedicosRespons.setLayout(pnlMedicosResponsLayout);
        pnlMedicosResponsLayout.setHorizontalGroup(
            pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrMedicosRespons, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRemovDosMedicosRespons))
                    .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                        .addComponent(lblCRMMedicoRespons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCRMMedicoRespons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarMedicoRespons)))
                .addContainerGap())
        );
        pnlMedicosResponsLayout.setVerticalGroup(
            pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosResponsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosResponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCRMMedicoRespons)
                    .addComponent(txtCRMMedicoRespons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMedicoRespons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrMedicosRespons, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemovDosMedicosRespons)
                .addContainerGap())
        );

        pnlTodosMedicos.setBorder(javax.swing.BorderFactory.createTitledBorder("Todos os médicos"));

        tblTodosMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Especialidade", "CRM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrTodosMedicos.setViewportView(tblTodosMedicos);

        btnAddAosMedicosRespons.setText("Adicionar aos médicos responsáveis");

        lblCRMMedico.setText("CRM:");

        btnBuscarDoPnlTodosMedicos.setText("Buscar na lista");

        javax.swing.GroupLayout pnlTodosMedicosLayout = new javax.swing.GroupLayout(pnlTodosMedicos);
        pnlTodosMedicos.setLayout(pnlTodosMedicosLayout);
        pnlTodosMedicosLayout.setHorizontalGroup(
            pnlTodosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTodosMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTodosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTodosMedicosLayout.createSequentialGroup()
                        .addComponent(scrTodosMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(pnlTodosMedicosLayout.createSequentialGroup()
                        .addComponent(btnAddAosMedicosRespons)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlTodosMedicosLayout.createSequentialGroup()
                        .addComponent(lblCRMMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCRMMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarDoPnlTodosMedicos)
                        .addContainerGap())))
        );
        pnlTodosMedicosLayout.setVerticalGroup(
            pnlTodosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTodosMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTodosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCRMMedico)
                    .addComponent(txtCRMMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDoPnlTodosMedicos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrTodosMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAosMedicosRespons)
                .addContainerGap())
        );

        btnAntDoPnlMedicos.setText("Anterior");
        btnAntDoPnlMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntDoPnlMedicosActionPerformed(evt);
            }
        });

        btnCancelarDoPnlMedicos.setText("Cancelar");
        btnCancelarDoPnlMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDoPnlMedicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMedicosLayout = new javax.swing.GroupLayout(pnlMedicos);
        pnlMedicos.setLayout(pnlMedicosLayout);
        pnlMedicosLayout.setHorizontalGroup(
            pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosLayout.createSequentialGroup()
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMedicosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAntDoPnlMedicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrarDoPnlMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarDoPnlMedicos))
                    .addGroup(pnlMedicosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlMedicosRespons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTodosMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMedicosLayout.setVerticalGroup(
            pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMedicosRespons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTodosMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarDoPnlMedicos)
                    .addComponent(btnAntDoPnlMedicos)
                    .addComponent(btnCancelarDoPnlMedicos))
                .addContainerGap())
        );

        lrpEtapasCadastro.setLayer(pnlDadosPessoais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lrpEtapasCadastro.setLayer(pnlFilhos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lrpEtapasCadastro.setLayer(pnlMedicos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lrpEtapasCadastroLayout = new javax.swing.GroupLayout(lrpEtapasCadastro);
        lrpEtapasCadastro.setLayout(lrpEtapasCadastroLayout);
        lrpEtapasCadastroLayout.setHorizontalGroup(
            lrpEtapasCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lrpEtapasCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(lrpEtapasCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lrpEtapasCadastroLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(lrpEtapasCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lrpEtapasCadastroLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        lrpEtapasCadastroLayout.setVerticalGroup(
            lrpEtapasCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lrpEtapasCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(lrpEtapasCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lrpEtapasCadastroLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlFilhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(lrpEtapasCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lrpEtapasCadastroLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lrpEtapasCadastro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lrpEtapasCadastro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProxDoPnlDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxDoPnlDadosActionPerformed
        pnlDadosPessoais.setVisible(false);
        pnlFilhos.setVisible(true);
        pnlMedicos.setVisible(false);
    }//GEN-LAST:event_btnProxDoPnlDadosActionPerformed

    private void btnProxPnlFilhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxPnlFilhosActionPerformed
        pnlDadosPessoais.setVisible(false);
        pnlFilhos.setVisible(false);
        pnlMedicos.setVisible(true);
    }//GEN-LAST:event_btnProxPnlFilhosActionPerformed

    private void btnAntPnlFilhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntPnlFilhosActionPerformed
        pnlDadosPessoais.setVisible(true);
        pnlFilhos.setVisible(false);
        pnlMedicos.setVisible(false);
    }//GEN-LAST:event_btnAntPnlFilhosActionPerformed

    private void tblFilhosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblFilhosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) tblFilhos.getModel();
            model.addRow(new Object[]{null, null, null, null, null, null});
        }
    }//GEN-LAST:event_tblFilhosKeyPressed

    private void btnAntDoPnlMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntDoPnlMedicosActionPerformed
        pnlDadosPessoais.setVisible(false);
        pnlFilhos.setVisible(true);
        pnlMedicos.setVisible(false);
    }//GEN-LAST:event_btnAntDoPnlMedicosActionPerformed

    private void btnCancelarPnlDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPnlDadosActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarPnlDadosActionPerformed

    private void btnCancelarDoPnlFilhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDoPnlFilhosActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarDoPnlFilhosActionPerformed

    private void btnCancelarDoPnlMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDoPnlMedicosActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarDoPnlMedicosActionPerformed

    private void ckbNaoPossuiAcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbNaoPossuiAcompActionPerformed
        if (ckbNaoPossuiAcomp.isSelected()) {
            setDadosAcompEnabled(false);
        } else {
            setDadosAcompEnabled(true);
        }
    }//GEN-LAST:event_ckbNaoPossuiAcompActionPerformed

    private void setDadosAcompEnabled(boolean isEnabled) {
        lblCPFAcomp.setEnabled(isEnabled);
        lblEmailAcomp.setEnabled(isEnabled);
        lblNomeAcomp.setEnabled(isEnabled);
        lblParentescoAcomp.setEnabled(isEnabled);
        lblRGAcomp.setEnabled(isEnabled);
        lblSexoAcomp.setEnabled(isEnabled);
        lblTelAcomp.setEnabled(isEnabled);
        txtCPFAcomp.setEnabled(isEnabled);
        txtEmailAcomp.setEnabled(isEnabled);
        txtNomeAcomp.setEnabled(isEnabled);
        txtParentescoAcomp.setEnabled(isEnabled);
        txtRGAcomp.setEnabled(isEnabled);
        txtTelAcomp.setEnabled(isEnabled);
        cmbSexoAcomp.setEnabled(isEnabled);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrMae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastrMae dialog = new TelaCadastrMae(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAosMedicosRespons;
    private javax.swing.JButton btnAddFilho;
    private javax.swing.JButton btnAntDoPnlMedicos;
    private javax.swing.JButton btnAntPnlFilhos;
    private javax.swing.JButton btnBuscarDoPnlTodosMedicos;
    private javax.swing.JButton btnBuscarMedicoRespons;
    private javax.swing.JButton btnCadastrarDoPnlMedicos;
    private javax.swing.JButton btnCancelarDoPnlFilhos;
    private javax.swing.JButton btnCancelarDoPnlMedicos;
    private javax.swing.JButton btnCancelarPnlDados;
    private javax.swing.JButton btnEditFilho;
    private javax.swing.JButton btnExcluirFilho;
    private javax.swing.JButton btnProxDoPnlDados;
    private javax.swing.JButton btnProxPnlFilhos;
    private javax.swing.JButton btnRemovDosMedicosRespons;
    private javax.swing.JCheckBox ckbNaoPossuiAcomp;
    private javax.swing.JComboBox<String> cmbSexoAcomp;
    private javax.swing.JLabel lblCPFAcomp;
    private javax.swing.JLabel lblCPFMae;
    private javax.swing.JLabel lblCRMMedico;
    private javax.swing.JLabel lblCRMMedicoRespons;
    private javax.swing.JLabel lblDataNascMae;
    private javax.swing.JLabel lblEmailAcomp;
    private javax.swing.JLabel lblNomeAcomp;
    private javax.swing.JLabel lblNomeMae;
    private javax.swing.JLabel lblParentescoAcomp;
    private javax.swing.JLabel lblRGAcomp;
    private javax.swing.JLabel lblRGMae;
    private javax.swing.JLabel lblSexoAcomp;
    private javax.swing.JLabel lblTelAcomp;
    private javax.swing.JLayeredPane lrpEtapasCadastro;
    private javax.swing.JPanel pnlAcompanhante;
    private javax.swing.JPanel pnlDadosPessoais;
    private javax.swing.JPanel pnlFilhos;
    private javax.swing.JPanel pnlMae;
    private javax.swing.JPanel pnlMedicos;
    private javax.swing.JPanel pnlMedicosRespons;
    private javax.swing.JPanel pnlTodosMedicos;
    private javax.swing.JScrollPane scrFilhos;
    private javax.swing.JScrollPane scrMedicosRespons;
    private javax.swing.JScrollPane scrTodosMedicos;
    private javax.swing.JPanel subPnlFilhos;
    private javax.swing.JTable tblFilhos;
    private javax.swing.JTable tblMedicosRespons;
    private javax.swing.JTable tblTodosMedicos;
    private javax.swing.JTextField txtCPFAcomp;
    private javax.swing.JTextField txtCPFMae;
    private javax.swing.JTextField txtCRMMedico;
    private javax.swing.JTextField txtCRMMedicoRespons;
    private javax.swing.JFormattedTextField txtDataNascMae;
    private javax.swing.JTextField txtEmailAcomp;
    private javax.swing.JTextField txtNomeAcomp;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtParentescoAcomp;
    private javax.swing.JTextField txtRGAcomp;
    private javax.swing.JTextField txtRGMae;
    private javax.swing.JTextField txtTelAcomp;
    // End of variables declaration//GEN-END:variables
}
